### PR TITLE
create hello world to appear on screen 

### LINKED ISSUE #5: [feature] Create hello world to appear on the screen
**Is your feature request related to a problem? Please describe.**
Currently, there are no problems faced

**Describe the solution you'd like**
Create hello world to appear on the screen

**Additional context**

#### Awesome :star::star::star::star::star:
https://github.com/JKUATSES/sesbot

### PR DESCRIPTION
**Pull request by bytecod3**
## Proposed changes
This pull request creates a splash screen to appear as the initial page on the Nextion Display 

## Types of changes

What types of changes does your code introduce to votingBooth?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Lint and unit tests pass locally with my changes
- [x] Kept pull request small so they can be easily reviewed.
- [x] Make sure not to introduce any compiler warnings.
- [x] AVOID breaking the continuous integration build.
- [x] AVOID making significant changes to the driver's overall architecture.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

### Does this close any currently open issues?
#5 

### Any relevant logs, error output, etc?
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

### Where has this been tested?

**Operating System:** Windows 10

**Platform:** win32

**Target Platform:** Nextion TFT-LCD Screen NX8048K070

**Toolchain Version:** …

**SDK Version:** …

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

## screenshots
Voting booth splash screen

### CODE REVIEW

**Comment by rodneyosodo** [comment]
Can you implement this?



or this

**Comment by rodneyosodo** [comment]
Use platform IO directory structure
> The libraries should be under libraries

**Comment by bytecod3** [comment]
Noted..

**Comment by bytecod3** [comment]
This is the revised splash screen. I have placed the header files under the  includes folder.
screen_shot

**Review by rodneyosodo — APPROVED** [review]
This looks great👍🏾. Keep on coding

**Comment by rodneyosodo** [comment]
Close #5

**Pull request merged**
